blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/EonsofStupid/connectome
    about: Report issues with the documentation here.
  - name: Security issues
    url: https://github.com/EonsofStupid/connectome/security/policy
    about: Report security vulnerabilities here.
